title: La rivisteria (PROVA)
description: Le riviste letterarie pinzate assieme
baseurl: "" # the subpath of your site, e.g. /blog
#url: "flexton.netlify.com" # the base hostname & protocol for your site, e.g. http://example.com

# Author
author-name:    La rivisteria
author-image:   1.jpg
author-job:     80+ Riviste letterarie e lit-blog 📚 | 1000+ Racconti 💬 | Ogni giorno ✨
author-email:   rivisteria@gmail.com # Add your email for contant form.
author-formspree:   f/xeqpkkjq # Add your Formspree endpoint
author-twitter: # Add your twitter account
author-instagram: larivisteria # Add your instagram account
about-author:   Sugli scaffali della Rivisteria, ogni giorno freschi di stampa, i racconti e gli articoli di tante molte riviste letterarie, ordinati per rivista e per data di pubblicazione, gli articoli di tante riviste letterarie online disseminate nel web.

# Copyright
copyright-name: Mario Barbarino

# Social settings
social-twitter:
social-facebook:
social-github:   
social-pinterest: 
social-instagram:
social-youtube:
social-vk:   
social-linkedin:

# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Google Analytics
google-analytics: G-6JKZTEBSJ9 # Add your identifier. For example UA-99631805-1

# Comment Section (Disqus)
disqus-identifier: larivisteria # Add your shortname for Disqus Comment. For example mr-brown

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-paginate

paginate: 15 # Number of posts in homepage
paginate_path: "/page/:num/"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
